spring.application.name=backend
Spring.datasource.url=jdbc:postgresql:localhost:5432/syria_db

spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true